### PR TITLE
Octoblu

### PR DESCRIPTION
**Pull request by edgarsilva**
Addresses issue #10

### CODE REVIEW

**Comment by edgarsilva** [comment]
@deadprogram fix conflicts and minor fixes, ready to merge.

**Comment by deadprogram** [comment]
Question: do we still need the coffeescript example? We have removed all the coffee at this point.

**Comment by deadprogram** [comment]
Also, would better to lock to a specific version of `meshblu` instead of `latest`, no?

**Comment by edgarsilva** [comment]
I agree with both assessments, let me remove coffee and check the current version of meshblue.

**Comment by deadprogram** [comment]
Thanks, @edgarsilva

**Pull request merged**
