### PR TITLE
Changed skynet npm to meshblu for latest updates

### PR DESCRIPTION
**Pull request by chrismatthieu**

### CODE REVIEW

**Comment by deadprogram** [comment]
Hi, @chrismatthieu I created a branch https://github.com/hybridgroup/cylon-skynet/tree/octoblu that should complete this PR, please take a look and try it out with your example if you have a moment. Thanks!

**Comment by chrismatthieu** [comment]
Good call. I noticed that it's missing a few other required updates.  I'll take a look.

**Comment by edgarsilva** [comment]
Travis build still failing on tests, any updates?

**Comment by edgarsilva** [comment]
@chrismatthieu it seems there are some merge conflicts due to latest changes in main master, could you pls merge master into your branch and solve the conflicts? Thanks.

**Comment by deadprogram** [comment]
@edgarsilva look my my branch `octoblu` for a better merged example of same.

**Comment by edgarsilva** [comment]
I see, @deadprogram are you gonna create a PR? should @chrismatthieu merge your branch with his? I guess we should only use one of this two branches/merges since it is basically the same.

**Comment by deadprogram** [comment]
My branch is more complete, should probably work from that one.

**Comment by edgarsilva** [comment]
I think this was already merged in another PR. @deadprogram correct? if so we can close this issue.

**Comment by deadprogram** [comment]
@edgarsilva looks like my branch was never merged, so still needs to be done. I think my branch is more complete, so would be good to look at it first.

**Comment by edgarsilva** [comment]
@deadprogram looking into it.

**Comment by edgarsilva** [comment]
is that the octoblue branch?

**Comment by deadprogram** [comment]
That is correct.

**Comment by edgarsilva** [comment]
@chrismatthieu & @deadprogram as mentioned above this was already implemented in another branch and has been merged.

Should be out in next release, @chrismatthieu thanks for the PR anyways.

**Pull request closed without merging**
